apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  namespace: "{{ .Values.namespace }}"
  name: "allow-service-{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
    owner: "{{ .Values.owner }}"

spec:
  ingress:
  -
    from:
    -
      podSelector:
        matchLabels:
          app: {{ .Values.name }}

  podSelector:
    matchLabels:
      app: {{ .Values.name }}
