apiVersion: v1
kind: Service

metadata:
  namespace: "{{ .Values.namespace }}"
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
    owner: "{{ .Values.owner }}"

spec:
  ports:
  -
    name: "{{ .Values.name }}"
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: 8080

  selector:
    app: {{ .Values.name }}

  type: LoadBalancer
