assetDir: static
publishDir: generated

baseURL: "//localhost:9300/"

caches:
  assets:
    dir: /tmp/hugo_cache/_gen
    maxAge: -1
  getcsv:
    dir: /tmp/hugo_cache/_gen
    maxAge: -1
  getjson:
    dir: /tmp/hugo_cache/_gen
    maxAge: -1
  images:
    dir: /tmp/hugo_cache/_gen
    maxAge: -1
  modules:
    dir: /tmp/hugo_cache/_gen
    maxAge: -1

languageCode: en-us
DefaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1

disableHugoGeneratorInject: true
#disableLiveReload: true

enableRobotsTXT: true

minificationOptions:
  KeepConditionalComments: false
  KeepEndTags: false

params:
  # custom dev params here
